### ISSUE TITLE
Encoding multiple files (Non GUI)

### ISSUE THREAD

**Issue by Maryada-27** [KEDRI-AUT/snn-encoder-tools#2]
is there a possible solution to encode more than one files (with EEG data), I noticed encodeButton_Callback is called as an event function for Encode button in GUI. I could call the event repeatedly for each file, however I am not sure if it is possible or if there is a better way to do it. 
Any suggestions?

**Comment by petrobalint** [comment]
You are encouraged to create your own non-gui version for your specific applications to suit your needs w.r.t. having multichannel data and multiple files. This can be done relatively easily via copy-pasting and tailoring the needed parts of the gui-version (make sure to remove the 'handles.' parts from variable names etc.), utilizing the additional functions that are in separate .m files. As a general guideline, I would recommend creating your custom script that encodes a single file correctly and than scaling this up by iterating through a set of files in a directory path while either saving your encoded signals and/or the optimal encoding parameters to a resulting file, or keeping everything in memory if you need that.

**Comment by Maryada-27** [comment]
Thanks for your detailed answer.
