### ISSUE TITLE
Have a problem in your article,MAYBE

### ISSUE THREAD

**Issue by Lizhanying-Sudo** [KEDRI-AUT/snn-encoder-tools#3]
Article Title:Selection and Optimization of Temporal Spike Encoding Methods for Spiking Neural Networks
[1](url) https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8689349&isnumber=8984609

I am reading this article, it is very helpful for my learning latterly. It is a great honor to read your article.
But, I find a little problem. In page 12, you described the Algorithm 4 BSA Encoding, ''if err1 <= (err2 ∗ threshold)'', i think '''(err2 -threshold)'. I can't understand ues  multiplication. 
If my thought is wrong, please tell me. thank you again!!!

**Comment by petrobalint** [comment]
Hello,
Thank you for your kind words.
Indeed in the original BSA, the threshold was a subtractive term with an
absolute value. However, that was for signals scaled between 0-1 min-max.
In this current approach, we do not scale the signal range, it can be
anything, e.g. 0-1 or 0-5000. Using the same absolute threshold value would
not work for all cases. A multiplicative threshold takes care of that.
Kind regards,
BP
